import React, { PropsWithChildren, useEffect, useMemo } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { getTokenFromLocalStorage } from '@/lib/common'
import { AuthPageContainer, FormWrapper } from '@/styles/components/Auth.styles'

const AuthLayout = ({ children }: PropsWithChildren) => {
  const router = useRouter()

  const pageTitle = useMemo(() => {
    const path = router.pathname
    return path === '/login'
      ? 'Log In - Calendar Events App'
      : 'Sign Up - Calendar Events App'
  }, [router])

  useEffect(() => {
    const localToken = getTokenFromLocalStorage()
    if (localToken) {
      router.push('/')
    }
  }, [router])

  return (
    <>
      <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AuthPageContainer>
          <FormWrapper>
            { children }
          </FormWrapper>
        </AuthPageContainer>
      </main>
    </>
  )
}

export default AuthLayout
