import React, { PropsWithChildren } from 'react'
import Head from 'next/head'
import Header from './Header'
import { useAuth } from '@/hooks/useAuth'

const Layout = ({ children }: PropsWithChildren) => {
  const { authenticated } = useAuth()

  return (
    <>
      <Head>
        <title>Calendar Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {authenticated && (
        <div>
          <Header />
          <div>
            {children}
          </div>
        </div>
      )}
    </>
  )
}

export default Layout
